services:
  - type: web
    name: web-petcare-ai
    env: node
    runtime: node
    nodeVersion: 22
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    branch: main
